version: '3.1'

services:
  jenkins:
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
    networks:
      - evidal

networks:
  evidal: